spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill
    username: root
    password: Tvgai36183

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.baluga.seckill.entity
  global-config:
    db-config:
      id-type: auto

server:
  port: 8080
